"""
github_tools.py
---------------
Tool for opening a Pull Request on GitHub.
This is the final step — after changes are committed and pushed.

Uses PyGithub library.
Install: pip install PyGithub
"""

from github import Github, GithubException


def open_pull_request(
    github_token: str,
    repo_full_name: str,
    branch_name: str,
    pr_title: str,
    pr_body: str,
    base_branch: str = "main"
) -> dict:
    """
    Open a Pull Request on GitHub from the agent's branch to main.

    Args:
        github_token:   Personal Access Token. From your .env file.
        repo_full_name: "username/repo-name" format.
                        Example: "niabob/my-project"
        branch_name:    The branch with the agent's changes.
                        Example: "fix/login-null-check"
        pr_title:       Title of the PR.
                        Example: "fix: resolve null pointer in login handler"
        pr_body:        Description of what was changed and why.
                        The LLM generates this automatically.
        base_branch:    The branch to merge INTO. Default is "main".
                        Change to "master" if the repo uses that.

    Returns:
        dict with:
            - success (bool)
            - pr_url (str): Direct link to the PR (if successful)
            - message (str): Status message
    """
    try:
        # Connect to GitHub using the token
        g = Github(github_token)

        # Get the repository object
        repo = g.get_repo(repo_full_name)

        # Create the Pull Request
        pr = repo.create_pull(
            title=pr_title,
            body=pr_body,
            head=branch_name,   # The branch with changes
            base=base_branch    # The branch to merge into
        )

        return {
            "success": True,
            "pr_url": pr.html_url,
            "pr_number": pr.number,
            "message": f"Pull Request #{pr.number} created successfully"
        }

    except GithubException as e:
        # GitHub API returned an error
        error_message = e.data.get("message", str(e)) if hasattr(e, "data") else str(e)
        return {
            "success": False,
            "pr_url": None,
            "message": f"GitHub API error: {error_message}"
        }

    except Exception as e:
        return {
            "success": False,
            "pr_url": None,
            "message": f"Unexpected error: {str(e)}"
        }


def extract_repo_name(github_url: str) -> str:
    """
    Extract 'username/repo-name' from a full GitHub URL.
    The PyGithub library needs this format.

    Example:
        Input:  "https://github.com/niabob/my-project"
        Output: "niabob/my-project"

    Args:
        github_url: Full GitHub URL.

    Returns:
        'username/repo-name' string, or empty string if parsing fails.
    """
    try:
        # Remove trailing slash if present
        url = github_url.rstrip("/")

        # Remove .git suffix if present
        if url.endswith(".git"):
            url = url[:-4]

        # Split by "/" and take the last two parts
        parts = url.split("/")
        if len(parts) >= 2:
            return f"{parts[-2]}/{parts[-1]}"

        return ""

    except Exception:
        return ""


def generate_pr_body(task: str, changed_files: list, test_result: dict) -> str:
    """
    Auto-generate a Pull Request description.
    The LLM can call this to create a structured PR body.

    Args:
        task:          The original task the developer gave the agent.
        changed_files: List of files that were modified.
        test_result:   The dict returned by run_tests().

    Returns:
        A formatted PR description string (Markdown).
    """
    files_list = "\n".join([f"- `{f}`" for f in changed_files]) or "- No files listed"

    test_status = "✅ All tests passed" if test_result.get("passed") else "❌ Tests failed"
    test_summary = test_result.get("summary", "No test summary available")

    pr_body = f"""## What this PR does

{task}

## Files changed

{files_list}

## Test results

{test_status}
`{test_summary}`

---
*This PR was automatically generated by ASDA-v1 (Autonomous Software Development Agent).*
*All changes were reviewed and confirmed by the developer before commit.*
"""

    return pr_body